import db from "../db/db.js"
import { addDoc, collection } from "firebase/firestore"


const productos = [
    {
        id:"DKs223",
        name:"Auriculares Redragon Scylla H901 PC",
        description:"Los auriculares Redragon Scylla H901 para PC ofrecen un sonido envolvente con alta calidad de audio.",
        stock:23,
        price:25500,
        image:["/img/auricular-1.webp","/img/auricular-1-2.webp", "/img/auricular-1-3.webp"],
        category:"perifericos",
    },  
    {
        id:"DKs453",
        name:"Auriculares Inalambricos Logitech G733 Lightspeed RGB White",
        description:"Disfruta de un audio inmersivo y libertad de movimiento con los Logitech G733 Lightspeed. Con tecnología inalámbrica de baja latencia.",
        stock:20,
        price:230900,
        image:[ "/img/auricular-2-removebg-preview.png", "/img/auricular-2-removebg-preview-2.png", "/img/auricular-2-removebg-preview-3.png"],
        category:"perifericos",
    },
    {
        id:"DKs15",
        name:"Auriculares Redragon Zeus X H510 RGB Surround",
        description:"Vive una experiencia de sonido envolvente con los Redragon Zeus X H510. Estos auriculares ofrecen audio 7.1 surround y cuentan con iluminación RGB personalizable.",
        stock:14,
        price:74500,
        image:["/img/auricular-3.png", "/img/auricular-3-2.png", "/img/auricular-3-3.png"],
        category:"perifericos",
    },
    {
        id:"RSTs100",
        name:"Teclado Mecanico Redragon Kumara K552 RGB Outemu Red",
        description:"Compacto y duradero, el Kumara K552 ofrece switches Outemu Red y retroiluminación RGB para una experiencia de juego fluida y personalizada.",
        stock:32,
        price:43000,
        image:["/img/teclado-1.png", "/img/teclado-1-2.png", "/img/teclado-1-3.png"],
        category:"perifericos",
    },
    {
        id:"RSTs142",
        name:"Teclado Redragon Harpe PRO K503 RGB ESP",
        description:"Teclado Redragon Harpe PRO K503 RGB, mecánico y ergonómico, con retroiluminación personalizable. Ideal para gamers.",
        stock:22,
        price:28000,
        image:["/img/teclado-2.png", "/img/telcado-2-2.jpg", "/img/teclado-2-3.png"],
        category:"perifericos",
    },
    {
        id:"RSTs150",
        name:"Teclado Mecanico Redragon Draconic K530W White RGB Wireless Switch Brown 60%",
        description:"Teclado mecánico compacto de 60%, con interruptores Brown para una escritura suave y silenciosa. Cuenta con retroiluminación RGB personalizable y conectividad inalámbrica, perfecto para gamers y usuarios que buscan rendimiento en espacios reducidos",
        stock:23,
        price:64700,
        image:["/img/teclado-3.png", "/img/teclado-3-2.png", "/img/teclado-3-3.png"],
        category:"perifericos",
    },    
    {
        id:"MSTs430",
        name:"Mouse Redragon Griffin M607 RGB Black",
        description:"Mouse RGB de alto rendimiento con diseño ergonómico y sensor preciso. Ideal para gamers, ofrece personalización de iluminación y botones programables, garantizando comodidad y precisión en cada movimiento.",
        stock:18,
        price:20500,
        image:["/img/mouse-1.jpg", "/img/mouse-1-2.jpg", "/img/mouse-1-3.jpg"],
        category:"perifericos",
    },
    {
        id:"MSTs124",
        name:"Mouse Logitech G903 Lightspeed Wireless HERO 25K",
        description:"Mouse inalámbrico de alto rendimiento con sensor HERO 25K, que ofrece una precisión extrema y una velocidad de respuesta ultrarrápida. Cuenta con botones programables, diseño ergonómico y una batería de larga duración, ideal para jugadores profesionales.",
        stock:10,
        price:115600,
        image:["/img/mouse-2.png", "/img/mouse-2-2.png", "/img/mouse-2-3.png"],
        category:"perifericos",
    },
    {
        id:"MSTs502",
        name:"Mouse Logitech G502 Lightspeed Wireless RGB Lightsync",
        description:"Mouse inalámbrico de alto rendimiento con sensor HERO y tecnología Lightspeed para una respuesta ultrarrápida. Incluye retroiluminación RGB Lightsync, botones programables y un diseño ergonómico, ideal para gamers que buscan precisión y personalización en cada juego.",
        stock:22,
        price:98500,
        image:["/img/mouse-3.jpg", "/img/mouse-3-2.jpg", "/img/mouse-3-3.jpg"],
        category:"perifericos",
    },
    {
        id:"KAAs2261",
        name:"Memoria GeiL DDR4 16GB (2x8GB) 3000MHz Super Luce RGB TUF Edition",
        description:"Ofrece alto rendimiento y estabilidad para sistemas de gaming y tareas exigentes, con un toque visual personalizado y duradero.",
        stock:25,
        price:57000,
        image:["/img/memoria-ram-1.webp", "/img/memoria-ram-1-2.webp"],
        category:"componentes",
    },
    {
        id:"KAAs3262",
        name:"Memoria GeiL DDR4 16GB 3000MHz Super Luce RGB Black",
        description:"Memoria DDR4 de 16GB a 3000MHz con retroiluminación RGB Super Luce. Ofrece alto rendimiento y estabilidad para gaming y multitarea, con un diseño elegante en color negro que agrega un toque visual único a tu PC.",
        stock:21,
        price:45700,
        image:["/img/memoria-ram-2-removebg-preview.png","/img/memoria-ram-2-2.webp"],
        category:"componentes",
    },
    {
        id:"KAAs342",
        name:"Fuente Corsair SFX 850W 80 Plus Gold Full Modular SF850L ITX SFX PCIe 5.0",
        description:"Compatible con sistemas ITX, incluye soporte PCIe 5.0, ideal para PCs compactos de alto rendimiento que requieren estabilidad y potencia.",
        stock:26,
        price:220500,
        image:["/img/fuente-1-removebg-preview.png", "/img/fuente-1-removebg-preview-2.png", "/img/fuente-1-removebg-preview-3.png"],
        category:"componentes",
    },
    {
        id:"KAAs112",
        name:"Placa de Video XFX Radeon RX 580 8GB GDDR5 GTS 2048SP",
        description:"Diseñada para ofrecer un rendimiento sólido en juegos y aplicaciones gráficas exigentes. Con 2048 procesadores de flujo, proporciona una experiencia visual fluida y detallada, ideal para gamers y creadores de contenido",
        stock:11,
        price:167000,
        image:["/img/placa-video-1-removebg-preview.png", "/img/placa-video-1-removebg-preview-2.png", "/img/placa-video-1-removebg-preview-3.png"],
        category:"componentes",
    },
    {
        id:"KAAs2",
        name:"Placa de Video ASUS Dual GeForce RTX 4060 Ti 8GB GDDR6 White OC",
        description:"Optimizada para un rendimiento excepcional en juegos y tareas de alto rendimiento. Su diseño en blanco y la tecnología OC permiten un rendimiento mejorado y una experiencia visual fluida y detallada. Ideal para gamers y entusiastas de la creación de contenido.",
        stock:15,
        price:590000,
        image:["/img/placa-video-2.png", "/img/placa-video-2-2.png", "/img/placa-video-2-3.png"],
        category:"componentes",
    },
    {
        id:"ASDs723",   
        name:"Placa de Video Asrock RX 5700 XT 8GB GDDR6 CHALLENGER PRO",
        description:"Diseñada para ofrecer un rendimiento potente en juegos y aplicaciones gráficas de alta demanda. Su arquitectura RDNA y tecnología de enfriamiento eficiente garantizan una experiencia visual fluida y de alta calidad. Ideal para gamers y creadores de contenido.",
        stock:14,
        price:540000,
        image:["/img/placa-video-3-removebg-preview.png", "/img/placa-video-3-removebg-preview-2.png", "/img/placa-video-3-removebg-preview-3.png"],
        category:"componentes",
    },
    {
        id:"AKks2344",
        name:"Mother Asrock B650I Lightning WIFI AM5 DDR5 ITX",
        description:"Diseño compacto ITX y conectividad Wi-Fi integrada. Ofrece rendimiento de última generación para procesadores AM5, ideal para sistemas de alto rendimiento en formatos pequeños.",
        stock:29,
        price:256000,
        image:["/img/mothers-1-removebg-preview.png", "/img/mothers-1-removebg-preview-2.png", "/img/mothers-1-removebg-preview-3.png"],
        category:"componentes",
    },
    {
        id:"KAAs1202",
        name:"Mother Gigabyte Z790 AORUS ELITE AX WIFI DDR4 S1700",
        description:"Con soporte para memoria DDR4 y socket S1700. Ofrece conectividad Wi-Fi integrada, opciones avanzadas de overclocking y rendimiento de alta gama, ideal para entusiastas del gaming y la creación de contenido.",
        stock:10,
        price:299000,
        image:["/img/mothers-2.png", "/img/mothers-2-2.png", "/img/mothers-2-3.png"],
        category:"componentes",
    },
    {
        id:"ASDs1203",
        name:"Monitor LG 29WQ600-W 29 UltraWide Full HD IPS",    
        description:"Con resolución Full HD y tecnología IPS. Ofrece una amplia área de visualización, colores precisos y ángulos de visión amplios, ideal para multitarea, trabajo creativo y entretenimiento.",
        stock:7,
        price:375000, 
        image:["/img/monitor-1-removebg-preview.png", "/img/monitor-1-removebg-preview-2.png", "/img/monitor-1-removebg-preview-3.png"],
        category:"accesorios",
    },
    {
        id:"ASDs1322",
        name:"Monitor Gamer Samsung Odyssey G3 27 VA FHD 165Hz",
        description:"Con panel VA, resolución Full HD y frecuencia de actualización de 165Hz. Ofrece una experiencia visual fluida y dinámica, ideal para juegos de alta velocidad y un rendimiento inmersivo.",
        stock:15,
        price:265000,
        image:["/img/monitor-2-removebg-preview.png", "/img/monitor-2-removebg-preview-2.png", "/img/monitor-2-removebg-preview-3.png"],
        category:"accesorios",
    },
    {
        id:"ASDs1122",
        name:"3000D RGB AIRFLOW - Blanco",
        description:"Diseñada para ofrecer un excelente flujo de aire y una gestión eficiente de cables. Incluye retroiluminación RGB para un estilo visual moderno y optimiza el enfriamiento de los componentes, ideal para sistemas de alto rendimiento.",
        stock:12,
        price:350000,
        image:["/img/gabinete-1.webp", "/img/gabinete-1-2.webp", "/img/gabinete-1-3.webp"],
        category:"accesorios",
    },
    {
        id:"ASDs223",
        name: "Gabinete Antec CX300 RGB ELITE Black 4x120mm RGB Fans Vidrio Templado 270°",
        description:"Con panel de vidrio templado de 270° y cuatro ventiladores RGB de 120mm. Ofrece un diseño moderno con excelente flujo de aire y un sistema de refrigeración eficiente, ideal para builds de alto rendimiento con un toque visual personalizado.",
        stock:19,
        price:562000,
        image:["/img/gabinete-2-removebg-preview.png", "/img/gabinete-2-removebg-preview-2.png", "/img/gabinete-2-removebg-preview-3.png"],
        category:"accesorios",
    },
]

const seedProducts = ()=> {
    const prodcutosRef = collection(db, "productos")
    productos.map(( { id, ...dataProduct })=> {
        addDoc(prodcutosRef, dataProduct)
    })
    console.log("productos subidos")
}

seedProducts()